### ISSUE TITLE
JDT crashes when opening Help -> Eclipse Marketplace

### ISSUE THREAD

**Issue by mjl269** [eclipse-jdt/eclipse.jdt#100]
JDT on Ubuntu 22.04 LTS crashes when opening Help -> Eclipse Marketplace. This also happens with the JEE version.
I looked for GTK errors in Bugzilla, but couldn't find this one.

The main error messages (see appended eclCrash.log) are:
Gtk-CRITICAL **: 18:15:57.794: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Gdk-CRITICAL **: 18:18:32.607: gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed

[lsb_release.log](https://github.com/eclipse-jdt/eclipse.jdt/files/15028520/lsb_release.log)
[hs_err_pid6635.log](https://github.com/eclipse-jdt/eclipse.jdt/files/15028521/hs_err_pid6635.log)
[eclCrash.log](https://github.com/eclipse-jdt/eclipse.jdt/files/15028522/eclCrash.log)

**Comment by mjl269** [comment]
GTK3 and GTK4 installed.

**Comment by iloveeclipse** [comment]
It is a webkit issue.
Please look at this query results https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+webkit and check if any of existing bugs matches.

**This** is  a JDT bug tracker and fully unrelated to webkit/SWT.
