### ISSUE TITLE
JEP 427 - Switch Pattern 3rd Preview

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt#12]
Refer to https://openjdk.java.net/jeps/427 for this JEP
- [x] eclipse-jdt/eclipse.jdt.core#55
- [x] eclipse-jdt/eclipse.jdt.ui#31

**Comment by akurtakov** [comment]
@mpalat What is the status of this one?

**Comment by jukzi** [comment]
@mpalat can this be closed?

**Comment by mpalat** [comment]
closing
