### ISSUE TITLE
eclipse-inst-jre-win64.exe detected as   Malicious.8b007b virus by Cybereason at virustotal

### ISSUE THREAD

**Issue by john3825** [eclipse-jdt/eclipse.jdt#24]
eclipse-inst-jre-win64.exe detected as   Malicious.8b007b virus by Cybereason at virustotal.

link:[fe66cd8a1cad96425d95c249172cb8502b60e9a0ff511e7d2adc2014bc287144
eclipse-inst-jre-win64.exe](https://www.virustotal.com/gui/file/fe66cd8a1cad96425d95c249172cb8502b60e9a0ff511e7d2adc2014bc287144?nocache=1)

**fe66cd8a1cad96425d95c249172cb8502b60e9a0ff511e7d2adc2014bc287144
eclipse-inst-jre-win64.exe**

**Cybereason: Malicious.8b007b**

Please fix.

**Comment by sravanlakkimsetti** [comment]
Notifications: @merks

**Comment by merks** [comment]
@mbarbero  This looks bogus to me.  I have no idea what this means.

**Comment by merks** [comment]
I think we should close this issue.  The reporter should provide/gather more information about why this is being flagged and can send an email to [security@eclipse.org](mailto:security@eclipse.org) if he feels it's necessary.

**Comment by john3825** [comment]
> 
I sent the request to [security@eclipse.org](mailto:security@eclipse.org). It is detected as a malicious app in [virustoal]{https://virustotal.com). Fix immediately.

**Comment by mbarbero** [comment]
Our investigations lead us to think that this is a false positive and we suggest you report the false positive to acronis - the tool flagging the file - following instructions from  https://kb.acronis.com/content/69412

**Comment by sravanlakkimsetti** [comment]
Closing this based on https://github.com/eclipse-jdt/eclipse.jdt/issues/24#issuecomment-1172164980
