### ISSUE TITLE
Update JDT.setup to use github URIs

### ISSUE THREAD

**Issue by merks** [eclipse-jdt/eclipse.jdt#3]
Only [eclipse.jdt](https://github.com/eclipse-jdt/eclipse.jdt) has migrated so far.  The other git clone tasks in the setup will need to be modified as additional repositories are migrated.

**Comment by merks** [comment]
Is it okay that I leave this open until all the repositories are migrated?

**Comment by iloveeclipse** [comment]
Sure

**Comment by merks** [comment]
The migration is complete and there is a configuration that is used here:

https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment
