### ISSUE TITLE
[20] Java 20 Effort

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt#40]
This is the top level bug for Java 20 across multiple repos.
- [x] https://github.com/eclipse-jdt/eclipse.jdt/issues/39
- [x] https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/145
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/548

**Comment by SarikaSinha** [comment]
@jarthana

**Comment by jarthana** [comment]
As of now, the following two preview revisions have been announced for Java 20:

- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/481
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/482

**Comment by mpalat** [comment]
- [20] JEP 430 String Templates #544

**Comment by mpalat** [comment]
-[ [20] JEP 430 String Templates ](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/544)

**Comment by akurtakov** [comment]
Java 20 is done deal for quite some time. Would you please close this one?
