### ISSUE TITLE
contributing guidelines contain outdated link for bug reports

### ISSUE THREAD

**Issue by joriki** [eclipse-jdt/eclipse.jdt#49]
https://github.com/eclipse-jdt/eclipse.jdt/blob/7196041c1a50d3f0625a0ad1d6447111ba4c3964/CONTRIBUTING#L33-L34

These links are outdated – they lead to a "404 File not found" error, and https://bugs.eclipse.org/bugs/enter_bug.cgi says that "JDT issues have moved to their respective repos in https://github.com/eclipse-jdt#reporting-issues".

**Comment by jarthana** [comment]
As you can see now on master branch, I have updated the [contribution guide](https://github.com/eclipse-jdt/eclipse.jdt/blob/master/CONTRIBUTING) to point to the right repos and remove the invalid bugzilla links.
