### ISSUE TITLE
JDT Javadoc issue in I20230405-1800 

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-jdt/eclipse.jdt#58]
https://download.eclipse.org/eclipse/downloads/drops4/I20230405-0600/compilelogs/jdt.doc.isv.javadoc.txt 

../../../eclipse.platform/ant/org.eclipse.ant.launching/src/org/eclipse/ant/launching/IAntLaunchConstants.java:17: error: package org.eclipse.core.externaltools.internal does not exist
import org.eclipse.core.externaltools.internal.IExternalToolConstants;
                                              ^
1 error

**Comment by iloveeclipse** [comment]
Please look at https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/484.
The problem is not new.
