### ISSUE TITLE
Update Oomph setup to make "rebase" default choice

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt#79]
See discussion on https://github.com/eclipse-egit/egit/issues/2.

People contributing via Oomph'ed installations should get `branch.autoSetupRebase=always` git preference set for all JDT repositories they clone.

The `.git/config` file should have these lines:

```
[branch]
	autoSetupRebase = always
```

Note, if `[branch]` section is already there, the `autoSetupRebase = always` line should be "appended" after the last line in the section.

**Comment by merks** [comment]
Very good.  I shall get to this shortly...

**Comment by merks** [comment]
I've done this across all the clone tasks of all the Eclipse TLP's setups.

Thanks for the excellent suggestion @iloveeclipse because I've been doing this manually every time I create topic branch.

I think you can close this now.

**Comment by iloveeclipse** [comment]
Thanks Ed for all the work!
